export type NormalizedJob = {
  title: string;
  company: string;
  description: string;
  descriptionHtml?: string | null;
  technologies: string[];
  requirements?: string[];
  benefits?: string[];
  responsibilities?: string[];
  area?: string | null;
  seniority?: string | null;
  modality?: string | null;
  location?: string | null;
  salaryMin?: number | null;
  salaryMax?: number | null;
  sourceUrl: string;
  provider: string;
  publishedAt: Date;
  contentHash: string;
  externalId: string;
};
